apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - mariadb.yaml
  - auth.yaml
  - cart.yaml
  - content.yaml
  - image.yaml
  - payments.yaml
  - products.yaml
  - api-gateway.yaml
  - ingress.yaml
