apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  labels:
    app: products-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
    spec:
      containers:
      - name: products-service
        image: products-service-dev:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3106
        envFrom:
        - configMapRef:
            name: ecommerce-config
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: products-service
  ports:
    - protocol: TCP
      port: 3106
      targetPort: 3106
  type: ClusterIP
