# syntax=docker/dockerfile:1.4

FROM node:20-alpine AS deps
WORKDIR /usr/src/app

RUN apk add --no-cache vips-dev python3 make g++ libc6-compat

COPY package*.json ./
COPY yarn.lock ./
COPY nest-cli.json ./
COPY tsconfig.json ./
COPY tsconfig.prod.json ./
COPY tsconfig.paths.json ./
COPY .swcrc.prod ./

RUN --mount=type=cache,target=/root/.yarn \
    yarn config set network-timeout 600000 && \
    yarn config set registry https://registry.npmjs.org/ && \
    yarn install --network-timeout 600000 --ignore-engines

FROM deps AS build
WORKDIR /usr/src/app

COPY api-gateway/ ./api-gateway/
COPY microservices/ ./microservices/
COPY shared/ ./shared/

RUN --mount=type=cache,target=/root/.swc \
    npx swc ./api-gateway/src -d dist && \
    npx swc ./microservices -d dist && \
    npx swc ./shared -d dist && \
    npx tsc-alias -p tsconfig.prod.json

FROM node:20-alpine AS runtime
WORKDIR /usr/src/app
ARG SERVICE_MAIN

RUN apk add --no-cache vips libc6-compat curl

COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production
ENV SERVICE_MAIN=${SERVICE_MAIN}

CMD ["sh", "-c", "node ${SERVICE_MAIN}"]
