apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"] # Usa spot para abaratar costos en pods prescindibles, y ondemand si spot no esta disponible
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["t3", "t3a", "c5", "m5"]
      nodeClassRef:
        name: default
  limits:
    cpu: 100
    memory: 1000Gi
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h # 30 dias de vida maxima por nodo antes de reciclarlo
