FROM node:20-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache \
    vips-dev \
    python3 \
    make \
    g++ \
    libc6-compat

RUN npm install -g nodemon ts-node tsconfig-paths

COPY microservices/payments/package*.json ./
COPY yarn.lock ./
COPY tsconfig.json ./
COPY tsconfig.paths.json ./

RUN yarn config set network-timeout 600000 && \
    yarn config set registry https://registry.npmjs.org/ && \
    yarn install --network-timeout 600000 || \
    npm install --registry https://registry.npmjs.org/ --timeout=600000

RUN yarn add -D tsconfig-paths

COPY microservices/auth/ ./src/
COPY shared/ ./shared/

EXPOSE 3101

CMD ["yarn", "start:dev"]