FROM node:20-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    libc6-compat

RUN npm install -g nodemon ts-node tsconfig-paths

# Copiar solo los archivos del servicio payments
COPY package*.json ./
COPY tsconfig.json ./

# Instalar dependencias del servicio
RUN npm install

# Copiar código fuente del servicio payments
COPY . .

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown -R appuser:appgroup /usr/src/app
USER appuser

EXPOSE 3105

CMD ["npm", "run", "start:dev"]
