FROM node:20-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache \
    vips-dev \
    python3 \
    make \
    g++ \
    libc6-compat

RUN npm install -g nodemon ts-node tsconfig-paths

COPY microservices/cart/package*.json .
COPY yarn.lock ./
COPY tsconfig.json ./
COPY tsconfig.paths.json ./

RUN yarn install --network-timeout 600000 && \
    yarn add @nestjs/typeorm typeorm mysql2 && \
    yarn add -D tsconfig-paths

COPY microservices/cart/ ./src/
COPY shared/ ./shared/

EXPOSE 3101

CMD ["yarn", "start:dev"]